name: EarthScope
title: ROVER - robust data access tool for FDSN data centers
markdown: kramdown
permalink: pretty
remote_theme: EarthScope/theme_ghpages
github_corner_link: https://github.com/EarthScope/rover
